### ISSUE TITLE
Censys Driver

### ISSUE THREAD

**Issue by karanshergill** [lanrat/certgraph#12]
When using the Censys driver an error is thrown:

`censys requires an appID and secret to run`

How to provide this?

**Comment by lanrat** [comment]
You need to provide the `-censys-appid` and `-censys-secret` flags which contain your Censys API credentials.

I just updated the readme with the usage on these two flags.

**Comment by karanshergill** [comment]
> You need to provide the `-censys-appid` and `-censys-secret` flags which contain your Censys API credentials.
> 
> I just updated the readme with the usage on these two flags.

Thank you!
