### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by Viss** [lanrat/certgraph#2]
not experienced with go, not really sure how to proceed

```
$ make
go build -ldflags "-X main.git_date=20171203 -X main.git_hash=f6222de1c56134ce1d33295803b359a87d4e7553" -o certgraph ./certgraph.go
# command-line-arguments
./certgraph.go:120:15: undefined: smtp.GetMX
make: *** [certgraph] Error 2

```

**Comment by lanrat** [comment]
Hmm, `smtp.GetMX` is defined inside [smtp.go](https://github.com/lanrat/certgraph/blob/master/driver/ssl/smtp/smtp.go).
I'm guessing your `$GOPATH` is not setup correctly so the compiler can't find the required files. You can learn more about how to set it up [here](https://golang.org/doc/code.html#GOPATH). Be sure to clone this repository inside `$GOPATH/github.com/lanrat/certgraph` on your system.

Alternatively, if you just want to run CertGraph, you can download pre-compiled binaries from the [releases tab](https://github.com/lanrat/certgraph/releases).

If the compilation is failing inside the correct GOPATH location let me know and I'll reopen the issue.
